import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 container mx-auto px-6 py-16 max-w-3xl">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: 10 March 2026</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Property Motion ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service. These terms constitute a legally binding agreement between
              you and Property Motion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">2. Description of Service</h2>
            <p>
              Property Motion is a SaaS platform that generates professional property videos, virtual staging, and photo
              enhancement for real estate agents. The Service includes AI-powered video generation, listing scraping,
              script generation, voiceover creation, and image processing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">3. Account Registration</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>You must provide accurate and complete registration information.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>One person or entity may not maintain more than one account.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">4. Subscriptions and Payment</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Paid plans are billed monthly via Stripe. Prices are in AUD unless otherwise stated.</li>
              <li>Your subscription renews automatically at the end of each billing period unless cancelled.</li>
              <li>You may cancel your subscription at any time. Access continues until the end of the current billing period.</li>
              <li>No refunds are provided for partial monthly billing periods. For annual plans, prorated refunds may be issued at our discretion.</li>
              <li>Video generation limits reset at the start of each billing period. Unused videos do not roll over.</li>
              <li>We reserve the right to change pricing with 30 days' notice. Existing subscriptions are honoured until their next renewal.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">5. Image and Content Rights</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                <strong>Your content:</strong> You retain all ownership rights to images you upload and content you create using the Service.
              </li>
              <li>
                <strong>License grant:</strong> By uploading images, you grant Property Motion a limited, non-exclusive licence to
                process, transform, and store those images solely for the purpose of providing the Service (video generation,
                enhancement, staging). This licence terminates when you delete the content or your account.
              </li>
              <li>
                <strong>Your warranty:</strong> You represent and warrant that you have the legal right to upload and use all images
                you submit. You must have permission from the property owner, photographer, or listing agent to use the images.
              </li>
              <li>
                <strong>Generated content:</strong> Videos, staged images, scripts, and audio generated by the Service are yours to
                use for commercial purposes (marketing, social media, MLS listings) subject to these Terms.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">6. MLS Compliance and Virtual Staging Disclosures</h2>
            <p>
              <strong>Important:</strong> Many MLS boards and real estate regulations require disclosure when property
              photos have been digitally altered. You are solely responsible for complying with applicable MLS rules,
              fair housing laws, and real estate regulations in your jurisdiction. Specifically:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Virtually staged images must be clearly labelled as "Virtually Staged" before being used in MLS listings.
                Our platform applies watermarks by default — do not remove them for MLS use.
              </li>
              <li>
                You must not use virtually staged images to misrepresent the condition, size, or features of a property.
              </li>
              <li>
                Under California AB 723 (effective January 2026), agents must provide access to original, unaltered images
                alongside any digitally modified photos.
              </li>
              <li>
                You must not use the Service to add or remove structural elements (windows, walls, rooms) or to
                conceal defects, damage, or material issues with a property.
              </li>
              <li>
                Property Motion provides tools to assist with compliance (watermarks, original image downloads) but does not
                guarantee compliance with any specific MLS board's rules. Consult your MLS board's policies.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">7. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for any unlawful purpose or to violate any laws.</li>
              <li>Upload images containing illegal content, copyrighted material you do not have rights to, or personally identifiable information of others without consent.</li>
              <li>Attempt to reverse-engineer, decompile, or extract the source code of the Service.</li>
              <li>Use automated tools, bots, or scripts to access the Service beyond normal usage.</li>
              <li>Circumvent usage limits, rate limits, or authentication mechanisms.</li>
              <li>Resell, sublicense, or redistribute the Service without written permission.</li>
              <li>Use the Service to create deceptive or misleading property representations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">8. Service Availability</h2>
            <p>
              We strive to maintain high availability but do not guarantee uninterrupted access. The Service depends on
              third-party providers (AI models, video rendering, payment processing) that may experience downtime.
              We are not liable for service interruptions caused by third-party provider outages, scheduled maintenance
              (with reasonable notice), or force majeure events.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Property Motion shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages, including but not limited to: loss of profits, data, or
              business opportunities; MLS violations or regulatory penalties arising from your use of generated content;
              or inaccuracies in AI-generated scripts or staging.
            </p>
            <p>
              Our total liability for any claim arising from these Terms or the Service shall not exceed the amount
              you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Property Motion, its officers, directors, employees, and agents
              from any claims, damages, losses, or expenses (including reasonable legal fees) arising from: your use of
              the Service; your violation of these Terms; your violation of any third-party rights (including intellectual
              property rights); or your violation of MLS rules or real estate regulations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">11. Termination</h2>
            <p>
              We may suspend or terminate your account if you violate these Terms, engage in fraudulent activity, or
              abuse the Service. Upon termination, your right to use the Service ceases immediately. We will retain
              your data for 90 days after termination to allow you to export it, after which it will be permanently deleted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">12. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the State of New South Wales, Australia.
              Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of New South Wales.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">13. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material changes at least 30 days before
              they take effect via email or an in-app notice. Continued use of the Service after changes take effect
              constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">14. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:hello@propertymotion.com" className="text-primary hover:underline">
                hello@propertymotion.com
              </a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
